spring:
  application:
    name: eureka-server
server:
  port: 8888

eureka:
  client:
    service-url:
    # eureka默认的服务地址空间信息配置
      defaultZone: http://localhost:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false
