spring:
  application:
    name: user-client

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    hostname: user-client-co
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
